### ISSUE TITLE
for options.type==3, move " u u' f f' b b'" cubits.to and cubits.from size mismatch

### ISSUE THREAD

**Issue by iamhuzhe-microleads** [godlikemouse/jquery.cube.threejs.js#1]
change 
    
    if(options.type > 3)

to 
   
    if(options.type >= 3)

**Comment by godlikemouse** [comment]
Thanks for bringing this to my attention, I'll check it out.

**Comment by godlikemouse** [comment]
Confirmed, I've fixed the issue under commit https://github.com/godlikemouse/jquery.cube.threejs.js/commit/28ad7636959f87dcf6afb620cde225e5f7198b7e.  Thanks.
